# Generated by Django 4.0.4 on 2022-06-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_jobdetails_jobdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetail',
            name='experience',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
